### ISSUE TITLE
escape_sequence node is omitting information

### ISSUE THREAD

**Issue by jgomezb11** [panekj/tree-sitter-yaml#9]
When trying to force a keyword or number into a string as in the following example:

    foo: "*"
    foo2: '&'
    number: '10'

The parsed result omits everything inside the double or single quotes, which means a loss of information compared to the initial file. Everything inside the quotes should be considered as a string and parsed as such, not omitted.

Or am I missing something?

**Comment by panekj** [comment]
I don't maintain this grammar
